import type { Metadata } from "next";
import { Comfortaa } from "next/font/google"; // Substituir Inter por Comfortaa
import "./globals.css";
import Header from '@/components/header';
import Footer from '@/components/footer';
import { Providers } from '@/contexts/Providers';

const comfortaa = Comfortaa({ subsets: ["latin"], weight: ["400", "700"] }); // Configurar Comfortaa

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={comfortaa.className}> {/* Alterar a classe de Inter para Comfortaa */}
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
